packages:
  - "packages/*"
  - "apps/*"
allowBuilds:
  '@clerk/shared': true
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "prisma"
  - "@clerk/shared"
